/**
 * Códigos de marcación internacional (lada) para el campo PHONE_LADA.
 * Nombres en español. Orden: México primero, luego alfabético en español.
 */
export interface CountryDialCode {
  name: string;
  dial: string;
  iso: string;
}

export const DEFAULT_DIAL_CODE = "+52";

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { name: "México", dial: "+52", iso: "MX" },
  { name: "Afganistán", dial: "+93", iso: "AF" },
  { name: "Albania", dial: "+355", iso: "AL" },
  { name: "Alemania", dial: "+49", iso: "DE" },
  { name: "Andorra", dial: "+376", iso: "AD" },
  { name: "Angola", dial: "+244", iso: "AO" },
  { name: "Antigua y Barbuda", dial: "+1268", iso: "AG" },
  { name: "Arabia Saudita", dial: "+966", iso: "SA" },
  { name: "Argelia", dial: "+213", iso: "DZ" },
  { name: "Argentina", dial: "+54", iso: "AR" },
  { name: "Armenia", dial: "+374", iso: "AM" },
  { name: "Australia", dial: "+61", iso: "AU" },
  { name: "Austria", dial: "+43", iso: "AT" },
  { name: "Azerbaiyán", dial: "+994", iso: "AZ" },
  { name: "Bahamas", dial: "+1242", iso: "BS" },
  { name: "Bangladés", dial: "+880", iso: "BD" },
  { name: "Barbados", dial: "+1246", iso: "BB" },
  { name: "Baréin", dial: "+973", iso: "BH" },
  { name: "Bélgica", dial: "+32", iso: "BE" },
  { name: "Belice", dial: "+501", iso: "BZ" },
  { name: "Benín", dial: "+229", iso: "BJ" },
  { name: "Bielorrusia", dial: "+375", iso: "BY" },
  { name: "Bolivia", dial: "+591", iso: "BO" },
  { name: "Bosnia y Herzegovina", dial: "+387", iso: "BA" },
  { name: "Botsuana", dial: "+267", iso: "BW" },
  { name: "Brasil", dial: "+55", iso: "BR" },
  { name: "Brunéi", dial: "+673", iso: "BN" },
  { name: "Bulgaria", dial: "+359", iso: "BG" },
  { name: "Burkina Faso", dial: "+226", iso: "BF" },
  { name: "Burundi", dial: "+257", iso: "BI" },
  { name: "Bután", dial: "+975", iso: "BT" },
  { name: "Cabo Verde", dial: "+238", iso: "CV" },
  { name: "Camboya", dial: "+855", iso: "KH" },
  { name: "Camerún", dial: "+237", iso: "CM" },
  { name: "Canadá", dial: "+1", iso: "CA" },
  { name: "Catar", dial: "+974", iso: "QA" },
  { name: "Chad", dial: "+235", iso: "TD" },
  { name: "Chile", dial: "+56", iso: "CL" },
  { name: "China", dial: "+86", iso: "CN" },
  { name: "Chipre", dial: "+357", iso: "CY" },
  { name: "Colombia", dial: "+57", iso: "CO" },
  { name: "Comoras", dial: "+269", iso: "KM" },
  { name: "Corea del Norte", dial: "+850", iso: "KP" },
  { name: "Corea del Sur", dial: "+82", iso: "KR" },
  { name: "Costa de Marfil", dial: "+225", iso: "CI" },
  { name: "Costa Rica", dial: "+506", iso: "CR" },
  { name: "Croacia", dial: "+385", iso: "HR" },
  { name: "Cuba", dial: "+53", iso: "CU" },
  { name: "Dinamarca", dial: "+45", iso: "DK" },
  { name: "Dominica", dial: "+1767", iso: "DM" },
  { name: "Ecuador", dial: "+593", iso: "EC" },
  { name: "Egipto", dial: "+20", iso: "EG" },
  { name: "El Salvador", dial: "+503", iso: "SV" },
  { name: "Emiratos Árabes Unidos", dial: "+971", iso: "AE" },
  { name: "Eritrea", dial: "+291", iso: "ER" },
  { name: "Eslovaquia", dial: "+421", iso: "SK" },
  { name: "Eslovenia", dial: "+386", iso: "SI" },
  { name: "España", dial: "+34", iso: "ES" },
  { name: "Estados Unidos", dial: "+1", iso: "US" },
  { name: "Estonia", dial: "+372", iso: "EE" },
  { name: "Esuatini", dial: "+268", iso: "SZ" },
  { name: "Etiopía", dial: "+251", iso: "ET" },
  { name: "Filipinas", dial: "+63", iso: "PH" },
  { name: "Finlandia", dial: "+358", iso: "FI" },
  { name: "Fiyi", dial: "+679", iso: "FJ" },
  { name: "Francia", dial: "+33", iso: "FR" },
  { name: "Gabón", dial: "+241", iso: "GA" },
  { name: "Gambia", dial: "+220", iso: "GM" },
  { name: "Georgia", dial: "+995", iso: "GE" },
  { name: "Ghana", dial: "+233", iso: "GH" },
  { name: "Granada", dial: "+1473", iso: "GD" },
  { name: "Grecia", dial: "+30", iso: "GR" },
  { name: "Guatemala", dial: "+502", iso: "GT" },
  { name: "Guinea", dial: "+224", iso: "GN" },
  { name: "Guinea-Bisáu", dial: "+245", iso: "GW" },
  { name: "Guinea Ecuatorial", dial: "+240", iso: "GQ" },
  { name: "Guyana", dial: "+592", iso: "GY" },
  { name: "Haití", dial: "+509", iso: "HT" },
  { name: "Honduras", dial: "+504", iso: "HN" },
  { name: "Hong Kong", dial: "+852", iso: "HK" },
  { name: "Hungría", dial: "+36", iso: "HU" },
  { name: "India", dial: "+91", iso: "IN" },
  { name: "Indonesia", dial: "+62", iso: "ID" },
  { name: "Irak", dial: "+964", iso: "IQ" },
  { name: "Irán", dial: "+98", iso: "IR" },
  { name: "Irlanda", dial: "+353", iso: "IE" },
  { name: "Islandia", dial: "+354", iso: "IS" },
  { name: "Islas Caimán", dial: "+1345", iso: "KY" },
  { name: "Islas Cook", dial: "+682", iso: "CK" },
  { name: "Islas Feroe", dial: "+298", iso: "FO" },
  { name: "Islas Maldivas", dial: "+960", iso: "MV" },
  { name: "Islas Marshall", dial: "+692", iso: "MH" },
  { name: "Islas Salomón", dial: "+677", iso: "SB" },
  { name: "Islas Vírgenes Británicas", dial: "+1284", iso: "VG" },
  { name: "Israel", dial: "+972", iso: "IL" },
  { name: "Italia", dial: "+39", iso: "IT" },
  { name: "Jamaica", dial: "+1876", iso: "JM" },
  { name: "Japón", dial: "+81", iso: "JP" },
  { name: "Jordania", dial: "+962", iso: "JO" },
  { name: "Kazajistán", dial: "+7", iso: "KZ" },
  { name: "Kenia", dial: "+254", iso: "KE" },
  { name: "Kirguistán", dial: "+996", iso: "KG" },
  { name: "Kiribati", dial: "+686", iso: "KI" },
  { name: "Kosovo", dial: "+383", iso: "XK" },
  { name: "Kuwait", dial: "+965", iso: "KW" },
  { name: "Laos", dial: "+856", iso: "LA" },
  { name: "Lesoto", dial: "+266", iso: "LS" },
  { name: "Letonia", dial: "+371", iso: "LV" },
  { name: "Líbano", dial: "+961", iso: "LB" },
  { name: "Liberia", dial: "+231", iso: "LR" },
  { name: "Libia", dial: "+218", iso: "LY" },
  { name: "Liechtenstein", dial: "+423", iso: "LI" },
  { name: "Lituania", dial: "+370", iso: "LT" },
  { name: "Luxemburgo", dial: "+352", iso: "LU" },
  { name: "Macao", dial: "+853", iso: "MO" },
  { name: "Macedonia del Norte", dial: "+389", iso: "MK" },
  { name: "Madagascar", dial: "+261", iso: "MG" },
  { name: "Malasia", dial: "+60", iso: "MY" },
  { name: "Malaui", dial: "+265", iso: "MW" },
  { name: "Malí", dial: "+223", iso: "ML" },
  { name: "Malta", dial: "+356", iso: "MT" },
  { name: "Marruecos", dial: "+212", iso: "MA" },
  { name: "Mauricio", dial: "+230", iso: "MU" },
  { name: "Mauritania", dial: "+222", iso: "MR" },
  { name: "Micronesia", dial: "+691", iso: "FM" },
  { name: "Moldavia", dial: "+373", iso: "MD" },
  { name: "Mónaco", dial: "+377", iso: "MC" },
  { name: "Mongolia", dial: "+976", iso: "MN" },
  { name: "Montenegro", dial: "+382", iso: "ME" },
  { name: "Mozambique", dial: "+258", iso: "MZ" },
  { name: "Myanmar (Birmania)", dial: "+95", iso: "MM" },
  { name: "Namibia", dial: "+264", iso: "NA" },
  { name: "Nauru", dial: "+674", iso: "NR" },
  { name: "Nepal", dial: "+977", iso: "NP" },
  { name: "Nicaragua", dial: "+505", iso: "NI" },
  { name: "Níger", dial: "+227", iso: "NE" },
  { name: "Nigeria", dial: "+234", iso: "NG" },
  { name: "Noruega", dial: "+47", iso: "NO" },
  { name: "Nueva Zelanda", dial: "+64", iso: "NZ" },
  { name: "Omán", dial: "+968", iso: "OM" },
  { name: "Países Bajos", dial: "+31", iso: "NL" },
  { name: "Pakistán", dial: "+92", iso: "PK" },
  { name: "Palaos", dial: "+680", iso: "PW" },
  { name: "Palestina", dial: "+970", iso: "PS" },
  { name: "Panamá", dial: "+507", iso: "PA" },
  { name: "Papúa Nueva Guinea", dial: "+675", iso: "PG" },
  { name: "Paraguay", dial: "+595", iso: "PY" },
  { name: "Perú", dial: "+51", iso: "PE" },
  { name: "Polonia", dial: "+48", iso: "PL" },
  { name: "Portugal", dial: "+351", iso: "PT" },
  { name: "Puerto Rico", dial: "+1787", iso: "PR" },
  { name: "Reino Unido", dial: "+44", iso: "GB" },
  { name: "República Centroafricana", dial: "+236", iso: "CF" },
  { name: "República Checa", dial: "+420", iso: "CZ" },
  { name: "República del Congo", dial: "+242", iso: "CG" },
  { name: "República Democrática del Congo", dial: "+243", iso: "CD" },
  { name: "República Dominicana", dial: "+1809", iso: "DO" },
  { name: "Ruanda", dial: "+250", iso: "RW" },
  { name: "Rumania", dial: "+40", iso: "RO" },
  { name: "Rusia", dial: "+7", iso: "RU" },
  { name: "Samoa", dial: "+685", iso: "WS" },
  { name: "San Cristóbal y Nieves", dial: "+1869", iso: "KN" },
  { name: "San Marino", dial: "+378", iso: "SM" },
  { name: "San Vicente y las Granadinas", dial: "+1784", iso: "VC" },
  { name: "Santa Lucía", dial: "+1758", iso: "LC" },
  { name: "Santo Tomé y Príncipe", dial: "+239", iso: "ST" },
  { name: "Senegal", dial: "+221", iso: "SN" },
  { name: "Serbia", dial: "+381", iso: "RS" },
  { name: "Seychelles", dial: "+248", iso: "SC" },
  { name: "Sierra Leona", dial: "+232", iso: "SL" },
  { name: "Singapur", dial: "+65", iso: "SG" },
  { name: "Siria", dial: "+963", iso: "SY" },
  { name: "Somalia", dial: "+252", iso: "SO" },
  { name: "Sri Lanka", dial: "+94", iso: "LK" },
  { name: "Sudáfrica", dial: "+27", iso: "ZA" },
  { name: "Sudán", dial: "+249", iso: "SD" },
  { name: "Sudán del Sur", dial: "+211", iso: "SS" },
  { name: "Suecia", dial: "+46", iso: "SE" },
  { name: "Suiza", dial: "+41", iso: "CH" },
  { name: "Surinam", dial: "+597", iso: "SR" },
  { name: "Tailandia", dial: "+66", iso: "TH" },
  { name: "Taiwán", dial: "+886", iso: "TW" },
  { name: "Tanzania", dial: "+255", iso: "TZ" },
  { name: "Tayikistán", dial: "+992", iso: "TJ" },
  { name: "Timor Oriental", dial: "+670", iso: "TL" },
  { name: "Togo", dial: "+228", iso: "TG" },
  { name: "Tonga", dial: "+676", iso: "TO" },
  { name: "Trinidad y Tobago", dial: "+1868", iso: "TT" },
  { name: "Túnez", dial: "+216", iso: "TN" },
  { name: "Turkmenistán", dial: "+993", iso: "TM" },
  { name: "Turquía", dial: "+90", iso: "TR" },
  { name: "Tuvalu", dial: "+688", iso: "TV" },
  { name: "Ucrania", dial: "+380", iso: "UA" },
  { name: "Uganda", dial: "+256", iso: "UG" },
  { name: "Uruguay", dial: "+598", iso: "UY" },
  { name: "Uzbekistán", dial: "+998", iso: "UZ" },
  { name: "Vanuatu", dial: "+678", iso: "VU" },
  { name: "Vaticano", dial: "+379", iso: "VA" },
  { name: "Venezuela", dial: "+58", iso: "VE" },
  { name: "Vietnam", dial: "+84", iso: "VN" },
  { name: "Yemen", dial: "+967", iso: "YE" },
  { name: "Yibuti", dial: "+253", iso: "DJ" },
  { name: "Zambia", dial: "+260", iso: "ZM" },
  { name: "Zimbabue", dial: "+263", iso: "ZW" },
];
