import "@fontsource/open-sauce-two/latin-300.css";
import "@fontsource/open-sauce-two/latin-400.css";
import "@fontsource/open-sauce-two/latin-500.css";
import "@fontsource/open-sauce-two/latin-600.css";
import "@fontsource/open-sauce-two/latin-700.css";
import "@fontsource/open-sauce-two/latin-800.css";
import "@fontsource/lora/latin-400.css";
import "@fontsource/lora/latin-400-italic.css";
import "@fontsource/lora/latin-600.css";
import "@fontsource/source-serif-4/latin-400.css";
import "@fontsource/source-serif-4/latin-600.css";
import "@fontsource/crimson-pro/latin-400.css";
import "@fontsource/crimson-pro/latin-400-italic.css";
import "@fontsource/crimson-pro/latin-600.css";
import "@fontsource/ibm-plex-sans/latin-400.css";
import "@fontsource/ibm-plex-sans/latin-500.css";
import "@fontsource/ibm-plex-sans/latin-600.css";
import "@fontsource/ibm-plex-mono/latin-400.css";
import "@fontsource/ibm-plex-mono/latin-500.css";
import "@fontsource/playfair-display/latin-400.css";
import "@fontsource/playfair-display/latin-600.css";
import "@fontsource/playfair-display/latin-400-italic.css";

export const OPEN_SAUCE_TWO_FAMILY = "'Open Sauce Two', system-ui, sans-serif";
